insert into projects (name, type, kind, device, status, icon, type_label, summary_es, summary_en, long_es, long_en, highlights_es, highlights_en, stack, published, sort_order) values
('Velamentum', '3d', 'front', 'browser', 'wip', 'box', '3D / E-COMMERCE',
 'Marca de ropa con configurador 3D. Blender a GLB, frontend Angular standalone.',
 'Clothing brand with a 3D configurator. Blender to GLB, standalone Angular frontend.',
 'Proyecto personal de marca: configurador 3D donde el usuario rota y personaliza prendas en tiempo real. Modelado en Blender, exportado a GLB y renderizado en Three.js sobre un frontend Angular standalone con servicios reactivos y rutas lazy. Backend en Spring Boot con esquema MySQL.',
 'Personal brand project: a 3D configurator where users rotate and customize garments in real time. Modeled in Blender, exported to GLB and rendered in Three.js over a standalone Angular frontend with reactive services and lazy routes. Spring Boot backend with a MySQL schema.',
 ARRAY['Configurador 3D interactivo con GLB optimizado', 'Componentes standalone + servicios reactivos', 'Identidad editorial blanco / negro / rojo'],
 ARRAY['Interactive 3D configurator with optimized GLB', 'Standalone components + reactive services', 'Editorial white / black / red identity'],
 ARRAY['Angular', 'Three.js', 'Blender', 'Spring Boot'],
 true, 0),
('controlPanel', 'web', 'front', 'browser', 'live', 'activity', 'DASHBOARD',
 'Panel de control con gráficos interactivos y datos de analítica en tiempo real.',
 'Control panel with interactive charts and real-time analytics data.',
 'Aplicación de panel de control que visualiza datos de analítica mediante gráficos interactivos. Enfoque en jerarquía de información, lectura rápida de métricas y componentes reutilizables.',
 'Control panel application that visualizes analytics data through interactive charts. Focused on information hierarchy, fast metric reading and reusable components.',
 ARRAY['Gráficos interactivos y filtrables', 'Layout de dashboard responsive', 'Componentes de datos reutilizables'],
 ARRAY['Interactive, filterable charts', 'Responsive dashboard layout', 'Reusable data components'],
 ARRAY['TypeScript', 'Charts', 'Angular'],
 true, 1),
('Cauce', 'tool', 'front', 'phone', 'wip', 'cpu', 'FINANCE APP',
 'App de finanzas personales para LATAM. Offline-first, resumen mensual 3D.',
 'Personal finance app for LATAM. Offline-first, 3D monthly summary.',
 'App móvil de finanzas personales para el mercado colombiano y LATAM. Arquitectura offline-first con SQLite local y un resumen mensual animado en 3D —''Tu historia financiera''— con TresJS. Identidad propia en terracota, violeta y near-black.',
 'Mobile personal finance app for the Colombian and LATAM market. Offline-first architecture with local SQLite and a 3D animated monthly summary —''Your financial story''— with TresJS. Own identity in terracotta, violet and near-black.',
 ARRAY['Offline-first con SQLite + Capacitor', 'Resumen mensual 3D con TresJS', 'Diseño propio: Instrument Serif + DM Sans'],
 ARRAY['Offline-first with SQLite + Capacitor', '3D monthly summary with TresJS', 'Own design: Instrument Serif + DM Sans'],
 ARRAY['Vue 3', 'Ionic', 'Capacitor', 'SQLite'],
 true, 2),
('Crud_usuarios', 'web', 'back', NULL, 'live', 'layers', 'FULL CRUD / API',
 'CRUD de usuarios con arquitectura modular y servicios reactivos.',
 'User CRUD with modular architecture and reactive services.',
 'Gestión completa de usuarios: alta, lectura, edición y borrado sobre una API REST. Arquitectura modular en TypeScript con separación clara de capas y validación de datos.',
 'Full user management: create, read, update and delete over a REST API. Modular TypeScript architecture with clear layer separation and data validation.',
 ARRAY['API REST con operaciones CRUD completas', 'Validación y manejo de errores', 'Arquitectura modular por capas'],
 ARRAY['REST API with full CRUD operations', 'Validation and error handling', 'Modular layered architecture'],
 ARRAY['TypeScript', 'Node.js', 'REST'],
 true, 3),
('chatBot', 'tool', 'back', NULL, 'archive', 'terminal', 'API / PYTHON',
 'API de chatbot en Python para automatización de respuestas.',
 'Chatbot API in Python for response automation.',
 'Servicio de chatbot construido en Python: recibe mensajes, los procesa y devuelve respuestas automatizadas a través de una API. Base para integraciones de soporte y automatización.',
 'Chatbot service built in Python: receives messages, processes them and returns automated responses through an API. A base for support and automation integrations.',
 ARRAY['Procesamiento de mensajes vía API', 'Respuestas automatizadas', 'Base para integraciones'],
 ARRAY['Message processing via API', 'Automated responses', 'Base for integrations'],
 ARRAY['Python', 'FastAPI'],
 true, 4),
('ClothingProject', 'web', 'front', 'browser', 'archive', 'layout', 'LANDING',
 'Prototipo de landing para tiendas de ropa, base visual de Velamentum.',
 'Landing prototype for clothing stores, the visual base of Velamentum.',
 'Primer prototipo de landing para tienda de ropa. Sirvió como exploración visual y base de la identidad que más tarde evolucionó en Velamentum.',
 'First landing prototype for a clothing store. It served as a visual exploration and the base of the identity that later evolved into Velamentum.',
 ARRAY['Exploración de identidad visual', 'Maquetación responsive', 'Origen del concepto Velamentum'],
 ARRAY['Visual identity exploration', 'Responsive layout', 'Origin of the Velamentum concept'],
 ARRAY['CSS', 'HTML'],
 true, 5);

insert into experience (company, role_es, role_en, period_es, period_en, tag_es, tag_en, is_current, summary_es, summary_en, points_es, points_en, stack, subprojects, sort_order) values
('Thomas Processing & Systems S.A.S.', 'Ingeniero de Desarrollo I', 'Development Engineer I', '2024 — 2026', '2024 — 2026', 'TIEMPO COMPLETO · ACTUAL', 'FULL-TIME · CURRENT', true,
 'Plataformas Angular para gestión electoral. De práctica profesional a Ingeniero de Desarrollo I.',
 'Angular platforms for electoral management. From internship to Development Engineer I.',
 ARRAY['Construcción de plataformas modulares con Angular Signals, lazy loading y control de acceso por roles', 'Integración de datos en tiempo real con AWS AppSync (WebSockets) y descargas con URL firmada', 'Promoción de práctica profesional a Ingeniero de Desarrollo I'],
 ARRAY['Built modular platforms with Angular Signals, lazy loading and role-based access control', 'Real-time data integration with AWS AppSync (WebSockets) and signed-URL downloads', 'Promoted from internship to Development Engineer I'],
 ARRAY['Angular 17–21', 'TypeScript', 'AWS AppSync', 'Lambda', 'S3', 'Tailwind', 'Azure DevOps'],
 '[{"name":"ThomasVote","desc_es":"Plataforma de gestión de boletines electorales: 6 módulos, Angular 17, Signals, lazy loading y RBAC.","desc_en":"Electoral bulletin management platform: 6 modules, Angular 17, Signals, lazy loading and RBAC."},{"name":"Monitor de Archivos","desc_es":"Dashboard en tiempo real (Angular 21 + Tailwind 4 + AWS AppSync) para seguimiento de archivos por departamento.","desc_en":"Real-time dashboard (Angular 21 + Tailwind 4 + AWS AppSync) for file tracking by department."}]'::jsonb,
 0),
('Velamentum', 'Fundador · Diseño & Desarrollo', 'Founder · Design & Development', 'EN CURSO', 'ONGOING', 'PROYECTO PROPIO · PARALELO', 'OWN PROJECT · PARALLEL', false,
 'Marca de ropa con visualización 3D interactiva. Diseño, modelado y desarrollo end-to-end.',
 'Clothing brand with interactive 3D visualization. End-to-end design, modeling and development.',
 ARRAY['Dirección de marca e identidad editorial', 'Modelado 3D en Blender + configurador web en Three.js', 'Frontend Angular standalone con backend Spring Boot'],
 ARRAY['Brand direction and editorial identity', '3D modeling in Blender + web configurator in Three.js', 'Standalone Angular frontend with Spring Boot backend'],
 ARRAY['Blender', 'Three.js', 'Angular', 'Spring Boot'],
 NULL,
 1),
('SIMPLE S.A.', 'Full Stack Developer', 'Full Stack Developer', '2023 — 2024', '2023 — 2024', 'TIEMPO COMPLETO', 'FULL-TIME', false,
 'Desarrollo full-stack sobre Angular y backend en Java/Node. (Detalle por confirmar contigo.)',
 'Full-stack development on Angular with Java/Node backend. (Detail to confirm with you.)',
 ARRAY['Desarrollo de features front-end en Angular', 'Servicios de backend en Java/Spring Boot y Node.js', 'Trabajo con base de datos MySQL', '[ Completar con logros y métricas reales ]'],
 ARRAY['Front-end feature development in Angular', 'Backend services in Java/Spring Boot and Node.js', 'Work with MySQL databases', '[ Fill in with real achievements and metrics ]'],
 ARRAY['Angular', 'Java / Spring Boot', 'Node.js', 'MySQL'],
 NULL,
 2),
('SENA — Bogotá', 'Tecnólogo en Análisis y Desarrollo de Sistemas', 'Systems Analysis & Development (Technologist)', 'FORMACIÓN', 'EDUCATION', 'TITULADO', 'GRADUATE', false,
 'Base formal en desarrollo de software, bases de datos y análisis de sistemas.',
 'Formal foundation in software development, databases and systems analysis.',
 ARRAY['Fundamentos de desarrollo full-stack', 'Modelado y gestión de bases de datos', 'Análisis y diseño de sistemas'],
 ARRAY['Full-stack development fundamentals', 'Database modeling and management', 'Systems analysis and design'],
 ARRAY['Programación', 'Bases de datos', 'Análisis de sistemas'],
 NULL,
 3);

insert into section_visibility (section, visible) values ('hero', true), ('manifesto', true), ('projects', true), ('experience', true), ('services', true), ('roadmap', true), ('contact', true);
